loadTimeData.data = {"a11yenhanced":"",
"bestScore":"最佳$1 $2 $3",
"bestScoreFlyout":"最高成绩: $1",
"bestScoreMenuDisplay":"$1 $2",
"bestScoreTopDisplay":"$1 $2 $3",
"buoyBestScore":-1,"buoyDescriptor":"条纹",
"buoyModeTitleInline":"之字形:",
"buoyTitle":"之字形",
"buoyUnit":"闸门",
"cancel":"取消",
"classicBestScore":-1,"classicDescriptor":"距离",
"classicModeTitleInline":"一起浪~:",
"classicTitle":"一起浪~",
"classicUnit":"m",
"close":"关闭",
"codeEdge":"作弊码已激活! $1",
"codeKonami":"忍者作弊码已激活! $1",
"codeMicrosoft":"苟利国家生死以，无限续命已激活! $1",
"codeScoring":"本轮成绩不计入最高成绩。",
"controllerAction":"按 $1",
"controllerSelect":"使用 $1",
"fontfamily":"system-ui, sans-serif",
"fontsize":"75%",
"gameCreditsButton":"积分",
"gameCreditsDialogTitle":"积分",
"gameMode":"模式切换到 $1",
"gameModeBuoy":"之字形",
"gameModeClassic":"一起浪~",
"gameModeSelectLabel":"模式",
"gameModeSelectLabelDisabled":"模式 (在新的一局里切换)",
"gameModeSpeed":"计时赛",
"gameSettings":"设置",
"highVisibilityActive":false,"highVisiblityModeToggleLabel":"高可见度模式",
"howToPlayBuoy":"通过尽量多的闸门！",
"howToPlayButton":"如何浪",
"howToPlayClassic":"浪的远的时候不要忘记躲避障碍物和章鱼哦~",
"howToPlayCoin":"收集钱币减一秒~",
"howToPlayControllerBoost":"按 RT 来让你跑得快",
"howToPlayControllerMovement":"用手柄或方向键来浪",
"howToPlayControllerRefresh":"按 LB+RB 以重新开始",
"howToPlayDialogTitle":"如何浪",
"howToPlayKeyboardBoost":"按 `F` 来让你跑得快",
"howToPlayKeyboardMovement":"用键盘的箭头或 `WASD` 键来冲浪",
"howToPlayKeyboardRefresh":"按 Ctrl+R 来刷新游戏",
"howToPlayLife":"撞击一次障碍掉一滴血",
"howToPlayMouseBoost":"双击以加速",
"howToPlayMouseMovement":"移动鼠标来浪",
"howToPlayMouseRefresh":"刷新页面以重新开始游戏",
"howToPlayShield":"从敌人手中救出小苟狗",
"howToPlaySpeed":"在最短时间内抵达终点",
"howToPlayTouchBoost":"双击以加速",
"howToPlayTouchMovement":"移动你的手指来冲浪",
"howToPlayTouchRefresh":"刷新以重新开始",
"keyboardAction":"spacebar",
"keyboardSelect":"用 $1",
"language":"en",
"lastSelectedMode":"经典",
"lastSelectedPlayer":6,"menuInfo":"$1 来选择浪人，用 $2 来浪",
"mouseAction":"双击",
"mouseSelect":"单击 $1",
"newBestScore":"新的最佳 $1 $2 $3",
"newGame":"开始新游戏",
"off":"关",
"on":"开",
"overInfo":"$1 来再浪一回",
"overTitle":"再浪一回",
"pauseInfo":"$1 来继续浪",
"pauseTitle":"游戏暂停",
"reducedSpeedActive":false,"reducedSpeedModeToggleLabel":"减速模式",
"resetAllStats":"重置所有数据",
"resetAllStatsDialogText":"你确定要重置所有数据吗？",
"resetAllStatsDialogTitle":"重置所有数据",
"specialThanks":"感谢:",
"speedBestScore":-1,"speedDescriptor":"时间",
"speedModeTitleInline":"计时赛:",
"speedTitle":"计时赛",
"speedUnit":"s",
"textdirection":"ltr",
"touchAction":"双击",
"touchSelect":"单击 $1"};
